homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: metric
  time_zone: !secret timezone
  packages: !include_dir_named packages

frontend:
config:
http:
  api_password: !secret http_password
updater:
discovery:
history:
logbook:
map:
sun:

#mqtt:
#  broker: 192.168.1.156
#  port: 1883
#  client_id: home-assistant-1
#  keepalive: 60
#  username: !secret mqtt_username
#  password: !secret mqtt_password


zwave:
  usb_path: /dev/ttyAMA0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/libopenzwave-0.3.3-py3.5-linux-armv7l.egg/config

device_tracker:
- platform: nmap_tracker
  hosts: 192.168.1.0/24
  track_new_devices: yes
  consider_home: 1800
  interval_seconds: 60
  home_interval: 5
  scan_options: " --privileged -sP "
  # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap   


deconz:
  host: 127.0.0.1
  api_key: !secret decons_api_key
  port: 80
  
sensor:
  - platform: plex


media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: true

ios:
  push:
    categories:
      - name: ALARM
        identifier: 'alarm'
        actions:
          - identifier: 'sound_alarm'
            title: 'ALARM'
            activationMode: 'background'
            destructive: yes
            behavior: 'default'
          - identifier: 'silence_alarm'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silence!'
            textInputPlaceholder: 'Placeholder'

notify:
  - name: ALARM_LIST
    platform: group
    services:
      - service: !secret phone_SS
      - service: !secret ipad_SS

recorder:
  purge_keep_days: 30
  purge_interval: 1
  exclude:
    domains:
      - automation
      - updater
      - sun
      - switch
      - script