homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: metric
  time_zone: !secret timezone

  customize: !include customize.yaml
  packages:
    pack_1: !include packages/system_overview.yaml
    pack_2: !include packages/weather.yaml
    pack_3: !include packages/pihole.yaml
    pack_4: !include packages/windy.yaml

frontend:
config:
http:
updater:
discovery:
history:
logbook:
map:
sun:

#sensor: !include_dir_merge_list sensors

sensor:
  - platform: plex

group: !include groups.yaml
#automation: !include_dir_list automations
#script: !include_dir_merge_list scripts

media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: true
