homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: metric
  time_zone: !secret timezone

  customize: !include customize.yaml
  packages:
    pack_1: !include packages/system_overview.yaml
    pack_2: !include packages/weather.yaml

frontend:
config:
http:
updater:
#discovery:
history:
logbook:
map:
sun:

#sensor: !include_dir_merge_list sensors

group: !include groups.yaml
automation: !include_dir_list automations
#script: !include_dir_merge_list scripts
