group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.temperaturer
      - group.Luftfuktighet
      - group.magnetsensorer
      - group.batteri
      - group.brannalarm
      - group.alarm
      - group.vacuum

  temperaturer:
    name: Temperatur
    entities:
      - sensor.dht_sensor_temperature
      - sensor.fibaro_system_fgsd002_smoke_sensor_temperature
      - sensor.gang
      - sensor.soverom
#      - sensor.temperature_158d0001e42477
#      - sensor.temperature_158d0001ab296f

      
  Luftfuktighet:
    name: Luftfuktighet
    entities:
      - sensor.dht_sensor_humidity
      - sensor.gang_2
      - sensor.soverom_3
#      - sensor.humidity_158d0001e42477
#      - sensor.humidity_158d0001ab296f
  
  magnetsensorer:
    name: Magnetsensorer
    entities:
      - binary_sensor.dor
#      - binary_sensor.door_window_sensor_158d00019f50b8
#      - binary_sensor.door_window_sensor_158d0001a985cc

  batteri:
    name: Batteri status
    entities:
      - sensor.zwave_batteri_brannalarm
      - sensor.iphone_stian_battery_level
      - sensor.stians_ipad_battery_level
      - sensor.vacuum_battery

  brannalarm:
    name: Brannalarm
    entities:
      - sensor.fibaro_system_fgsd002_smoke_sensor_alarm_level
      - sensor.fibaro_system_fgsd002_smoke_sensor_alarm_type
      - sensor.fibaro_system_fgsd002_smoke_sensor_burglar
      - sensor.fibaro_system_fgsd002_smoke_sensor_general
      - sensor.fibaro_system_fgsd002_smoke_sensor_heat
      - sensor.fibaro_system_fgsd002_smoke_sensor_heat_2
      - sensor.fibaro_system_fgsd002_smoke_sensor_power_management
      - sensor.fibaro_system_fgsd002_smoke_sensor_smoke
      - sensor.fibaro_system_fgsd002_smoke_sensor_smoke_2
      - sensor.fibaro_system_fgsd002_smoke_sensor_sourcenodeid
      - sensor.fibaro_system_fgsd002_smoke_sensor_system
 
  alarm:
    name: Alarms
    entities:
      - automation.brannalarm
      - automation.Hoveddor_alarm
      - automation.Vindu_alarm
      - automation.zec_mining
      - automation.aeon_mining
      - automation.aksjenedlasting
      - automation.server_cpu_temperatur


  vacuum:
    name: Stovsuger
    entities:
      - vacuum.xiaomi_vacuum_cleaner
      - automation.Automatisk_stovsuging
      - sensor.vacuum_status
      - sensor.vacuum_main_brush_left
      - sensor.vacuum_side_brush_left
      - sensor.vacuum_filter_left
      
sensor:
  - platform: dht
    sensor: DHT22
    pin: 23
    monitored_conditions:
      - temperature
      - humidity

  - platform: template
    sensors:
      zwave_batteri_brannalarm:
        value_template: '{{ states.zwave.fibaro_system_fgsd002_smoke_sensor.attributes.battery_level|default(0) }}'
        icon_template: >
          {% set battery_level = states.zwave.fibaro_system_fgsd002_smoke_sensor.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}

  - platform: template
    sensors:
      vacuum_battery:
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}'
        icon_template: >
          {% set battery_level = states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
      vacuum_status:
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}'
      vacuum_side_brush_left:
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.side_brush_left }}'
      vacuum_main_brush_left:
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.main_brush_left }}'
      vacuum_filter_left:
        value_template: '{{ states.vacuum.xiaomi_vacuum_cleaner.attributes.filter_left }}'
        
vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_host
    token: !secret vacuum_token

#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - key: !secret gateway_key    
          
homeassistant:
    customize:
      sensor.fibaro_system_fgsd002_smoke_sensor_temperature:
        friendly_name: Brannalarm
#        icon: mdi code....
        unit_of_measurement: °C
      sensor.zwave_batteri_brannalarm:
        friendly_name: Brannalarm
      sensor.iphone_stian_battery_level:
        friendly_name: Iphone
      sensor.stians_ipad_battery_level:
        friendly_name: Ipad
      sensor.vacuum_battery:
        friendly_name: Støvsuger
      sensor.vacuum_status:
        friendly_name: Status
      sensor.vacuum_main_brush_left:
        friendly_name: Hovedbørste - tid til bytte
        unit_of_measurement: h
      sensor.vacuum_side_brush_left:
        friendly_name: Sidebørste - tid til bytte
        unit_of_measurement: h
      sensor.vacuum_filter_left:
        friendly_name: Filter - tid til bytte
        unit_of_measurement: h
#      sensor.temperature_158d0001e42477:
#        friendly_name: Soverom Temperatur
#      sensor.pressure_158d0001e42477:
#        friendly_name: Soverom Trykk
#      sensor.humidity_158d0001e42477:
#        friendly_name: Soverom Luftfuktighet
#      sensor.illumination_34ce00fa7cf0:
#        friendly_name: stue lysstyrke
#      sensor.temperature_158d0001ab296f:
#        friendly_name: Gang Temperatur
#      sensor.pressure_158d0001ab296f:
#        friendly_name: Gang Trykk
#      sensor.humidity_158d0001ab296f:
#        friendly_name: Gang Luftfuktighet
#      binary_sensor.door_window_sensor_158d00019f50b8:
#        friendly_name: Hoveddør
#      binary_sensor.door_window_sensor_158d0001a985cc:
#        friendly_name: Vindu
      

        
automation:
  - alias: Brannalarm
    trigger:
      platform: numeric_state
      entity_id:
        - sensor.fibaro_system_fgsd002_smoke_sensor_smoke_2
        - sensor.fibaro_system_fgsd002_smoke_sensor_smoke
      above: 0
    action:
      service: notify.ALARM_LIST
      data:
        message: "Alarm - brannalarm"
        data:
          push:
            badge: 5
            category: 'alarm'

  - alias: Automatisk støvsuging
    trigger:
      - platform: state
        entity_id: device_tracker.iphone_stian
        to: 'not_home'
        for:
          hours: 1
      - platform: time
        at: '13:00:00'
    condition:
      condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      - service: homeassistant.turn_on
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: Hoveddor alarm
    trigger:
      - platform: state
        entity_id: binary_sensor.dor
        from: 'off'
        to: 'on'
    action:
      service: notify.ALARM_LIST
      data:
        message: "Alarm - Hoveddør"
        data:
          push:
            badge: 5
            category: 'alarm'

#  - alias: Vindu alarm
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.door_window_sensor_158d0001a985cc
#        from: 'off'
#        to: 'on'
#    action:
#      service: notify.ALARM_LIST
#      data:
#        message: "Alarm - Vindu"
#        data:
#          push:
#            badge: 5
#            category: 'alarm'            
        