# after disabling pihole dns cache needs to be cleared
# open cmd as admin and run
# ipconfig /flushdns
# ref link
# https://community.home-assistant.io/t/pi-hole-switch/22004
#
#
# to find auth code
# login to pihole
# settings
# under API press show API token then yes, show API token
#
#
# Adding SSH access to pi hole
#
# homeassistant ip: 192.168.1.156
# homeassistant user: homeassistant
# pihole ip: 192.168.1.2
# pihole user: pi
#
# sudo su -s /bin/bash homeassistant                                                 # to login with homeassistant user
# ssh-keygen -t rsa
# /home/homeassistant/.ssh/__UNIQUE_NAME__                                           # if multiple ssh points is needed add unique name else enter
# enter                                                                              # no password eases the HA connecting part
# ssh pi@192.168.1.2 mkdir -p .ssh                                                   # login to the host ip address to create an .ssh folder to store the public key in
# cat .ssh/__UNIQUE_NAME__.pub | ssh pi@192.168.1.2 'cat >> .ssh/authorized_keys'    # add the public key to the pihole
#
# echo 'IdentityFile ~/.ssh/__UNIQUE_NAME__' >> ~/.ssh/config                        # to instruct ssh to try multiple keys in succession when connecting ref. https://stackoverflow.com/questions/2419566/best-way-to-use-multiple-ssh-private-keys-on-one-client
# 
# test if it works:
# ssh pi@192.168.1.2                                                                 # if it goes through without asking for password it works 
#
#
#   source:
#   https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/

homeassistant:
  customize:
    sensor.pihole_ads_percentage_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pihole_domains_being_blocked:
      friendly_name: Total Domains Blocking
      icon: mdi:do-not-disturb

    sensor.pihole_dns_unique_clients:
      friendly_name: Unique Clients
      icon: mdi:desktop-classic

    sensor.pihole_ads_blocked_today:
      friendly_name: Ads Blocked Today
      icon: mdi:do-not-disturb

    sensor.pihole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

#    group.pihole:
#      homebridge_hidden: true

sensor:
  - platform: pi_hole
    host: 192.168.1.2
    monitored_conditions:
      - dns_queries_today
      - ads_blocked_today
      - ads_percentage_today
      - unique_clients

switch:
  - platform: command_line
    switches:
      disable_pihole:
        command_on: !secret pihole_disable_on
        command_off: !secret pihole_disable_off
#        command_state: !secret pihole_state
#        value_template: "{{ value_json.status == 'enabled' }}

group:
  pihole:
    entities:
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_today
      - sensor.pihole_ads_percentage_blocked_today
      - switch.disable_pihole
      - script.update_pihole
      - script.restart_pihole

script:
  update_pihole:
    alias: Update PiHole
    sequence:
      - service: shell_command.updatepihole
        entity_id: script.update_pihole               

  restart_pihole:
    alias: Restart PiHole
    sequence:
      - service: shell_command.rebootpihole
        entity_id: script.restart_pihole
        
shell_command:
  updatepihole: ssh pi@192.168.1.2 sudo /home/pi/update.sh
  rebootpihole: ssh pi@192.168.1.2 sudo reboot