group:
  weather:
    name: Weather
    icon: mdi:weather-cloudy
    view: yes
    entities:
      - group.yr_weather
      - group.weather_forecast
      - group.weather_history

  Yr weather:
    - sensor.weather_symbol
    - sensor.weather_temperature
    - sensor.weather_precipitation
    - sensor.weather_pressure
    - sensor.weather_humidity
    - sensor.weather_cloudiness
    - sensor.weather_high_clouds
    - sensor.weather_medium_clouds
    - sensor.weather_low_clouds
    - sensor.weather_fog
    - sensor.weather_dewpoint_temperature
    - sensor.weather_wind_direction
    - sensor.weather_wind_speed

  Weather forecast:
    - camera.weather_forecast_Oslo

  Weather history:
    - history_graph.temperature
    - history_graph.precipitation
    - history_graph.pressure

history_graph:
  gr1:
    name: Temperature
    entities:
      - sensor.weather_temperature
    hours_to_show: 720
    refresh: 60
  gr2:
    name: Precipitation
    entities:
      - sensor.weather_precipitation
    hours_to_show: 720
    refresh: 60
  gr3:
    name: Pressure
    entities:
      - sensor.weather_pressure
    hours_to_show: 720
    refresh: 60

sensor:
  - platform: yr
    name: Weather 
    monitored_conditions:
      - symbol
      - temperature
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

camera:
  - platform: generic
    name: Weather forecast Oslo
    still_image_url: https://www.yr.no/place/Norway/Oslo/Oslo/Oslo/meteogram.svg
    content_type: 'image/svg+xml'